project:
  name: fraud-detection
  version: "1.0.0"

data:
  raw_path: "data/raw/creditcard.csv"
  processed_path: "data/processed/processed_data.csv"
  test_size: 0.2
  random_state: 42

model:
  type: "RandomForestClassifier"
  save_path: "models/"
  
training:
  random_state: 42
  cv_folds: 5
  
mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "fraud_detection"
  
serving:
  host: "0.0.0.0"
  port: 8000
  model_version: "v1"